name: 3OutcomesMastodon

on:
  workflow_dispatch:
  schedule:
    - cron: '23 15-18 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: find 3 true outcomes and post
      run: |
        python main.py
      env:
          MASTODON_API_TOKEN: ${{ secrets.MASTODON_API_TOKEN }}
    - name: commit
      run: |
        # Stage the file, commit and push
        git config user.email "matthew.n.nicholson1@gmail.com"
        git config user.name "Matt Nicholson"
        git pull
        git add *
        git commit -m "completed run for `date +'%Y-%m-%d'`"
        git push
